// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: grpc_apiproxy.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqSendEmailBindCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqSendEmailBindCode) Reset() {
	*x = ReqSendEmailBindCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendEmailBindCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendEmailBindCode) ProtoMessage() {}

func (x *ReqSendEmailBindCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendEmailBindCode.ProtoReflect.Descriptor instead.
func (*ReqSendEmailBindCode) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSendEmailBindCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqSendEmailBindCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ReqSendEmailResetPasswordValidationCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqSendEmailResetPasswordValidationCode) Reset() {
	*x = ReqSendEmailResetPasswordValidationCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendEmailResetPasswordValidationCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendEmailResetPasswordValidationCode) ProtoMessage() {}

func (x *ReqSendEmailResetPasswordValidationCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendEmailResetPasswordValidationCode.ProtoReflect.Descriptor instead.
func (*ReqSendEmailResetPasswordValidationCode) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ReqSendEmailResetPasswordValidationCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqSendEmailResetPasswordValidationCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ReqSendMsgToTelegram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bot string `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	Msg []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReqSendMsgToTelegram) Reset() {
	*x = ReqSendMsgToTelegram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendMsgToTelegram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendMsgToTelegram) ProtoMessage() {}

func (x *ReqSendMsgToTelegram) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendMsgToTelegram.ProtoReflect.Descriptor instead.
func (*ReqSendMsgToTelegram) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSendMsgToTelegram) GetBot() string {
	if x != nil {
		return x.Bot
	}
	return ""
}

func (x *ReqSendMsgToTelegram) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_grpc_apiproxy_proto protoreflect.FileDescriptor

var file_grpc_apiproxy_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x53, 0x0a, 0x27, 0x52, 0x65,
	0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x3a, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x54,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x6f, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xe8, 0x01, 0x0a, 0x0c,
	0x41, 0x50, 0x49, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x52, 0x50, 0x43, 0x12, 0x3a, 0x0a, 0x11,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x19, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x60, 0x0a, 0x24, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2c, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x11, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x12,
	0x19, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67,
	0x54, 0x6f, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_apiproxy_proto_rawDescOnce sync.Once
	file_grpc_apiproxy_proto_rawDescData = file_grpc_apiproxy_proto_rawDesc
)

func file_grpc_apiproxy_proto_rawDescGZIP() []byte {
	file_grpc_apiproxy_proto_rawDescOnce.Do(func() {
		file_grpc_apiproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_apiproxy_proto_rawDescData)
	})
	return file_grpc_apiproxy_proto_rawDescData
}

var file_grpc_apiproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_apiproxy_proto_goTypes = []interface{}{
	(*ReqSendEmailBindCode)(nil),                    // 0: mpb.ReqSendEmailBindCode
	(*ReqSendEmailResetPasswordValidationCode)(nil), // 1: mpb.ReqSendEmailResetPasswordValidationCode
	(*ReqSendMsgToTelegram)(nil),                    // 2: mpb.ReqSendMsgToTelegram
	(*Empty)(nil),                                   // 3: mpb.Empty
}
var file_grpc_apiproxy_proto_depIdxs = []int32{
	0, // 0: mpb.APIProxyGRPC.SendEmailBindCode:input_type -> mpb.ReqSendEmailBindCode
	1, // 1: mpb.APIProxyGRPC.SendEmailResetPasswordValidationCode:input_type -> mpb.ReqSendEmailResetPasswordValidationCode
	2, // 2: mpb.APIProxyGRPC.SendMsgToTelegram:input_type -> mpb.ReqSendMsgToTelegram
	3, // 3: mpb.APIProxyGRPC.SendEmailBindCode:output_type -> mpb.Empty
	3, // 4: mpb.APIProxyGRPC.SendEmailResetPasswordValidationCode:output_type -> mpb.Empty
	3, // 5: mpb.APIProxyGRPC.SendMsgToTelegram:output_type -> mpb.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_apiproxy_proto_init() }
func file_grpc_apiproxy_proto_init() {
	if File_grpc_apiproxy_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_apiproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendEmailBindCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendEmailResetPasswordValidationCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendMsgToTelegram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_apiproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_apiproxy_proto_goTypes,
		DependencyIndexes: file_grpc_apiproxy_proto_depIdxs,
		MessageInfos:      file_grpc_apiproxy_proto_msgTypes,
	}.Build()
	File_grpc_apiproxy_proto = out.File
	file_grpc_apiproxy_proto_rawDesc = nil
	file_grpc_apiproxy_proto_goTypes = nil
	file_grpc_apiproxy_proto_depIdxs = nil
}
