// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: grpc_account.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//	message ReqLoginByPassword {
//	   string account = 1;
//	   string password = 2;
//	   string remote_ip = 3;
//	   string region = 4;
//	}
//
//	message ResLoginByPassword {
//	   AccountInfo account = 1;
//	   string resources = 2;
//	   string token = 3;
//	}
//
//	message ReqGetAccountInfo {
//	   string account = 1;
//	}
//
//	message ReqRegisterAccount {
//	   string account = 1;
//	   string password = 2;
//	   string device = 3;
//	   string os = 4;
//	   string device_id = 5;
//	   string client_version = 6;
//	   string region = 7;
//	   string remote_ip = 8;
//	   string platform = 9;
//	}
//
//	message ResGenerateNonce {
//	   string nonce = 1;
//	}
//
//	message ReqWebLoginByWallet {
//	   string wallet_addr = 1;
//	   bytes pub_key = 2;
//	   string nonce = 3;
//	   string remote_ip = 4;
//	   string region = 5;
//	   string aptos_full_msg = 6;
//	   string aptos_signature = 7;
//	}
//
//	message ResWebLoginByWallet {
//	   AccountInfo account = 1;
//	   string resources = 2;
//	   string token = 3;
//	}
//
//	message ReqGetAccountInfoByAccount {
//	   string account = 1;
//	}
//
//	message ReqGenerateAndSendEmailBindCode {
//	   string email = 1;
//	}
//
//	message ReqWebBindEmail {
//	   uint64 user_id = 1;
//	   string email = 2;
//	   string code = 3;
//	}
//
//	message ResWebBindEmail {
//	   AccountInfo account = 1;
//	   string resources = 2;
//	   string token = 3;
//	}
//
//	message ResGetAptosAccount {
//	   string aptos_acc_addr = 1;
//	   string pub_key = 2;
//	}
//
//	message ReqChangePassword {
//	   uint64 user_id = 1;
//	   string old_password = 2;
//	   string new_password = 3;
//	}
//
//	message ReqSendEmailResetPasswordCode {
//	   string email = 1;
//	}
//
//	message ReqCheckEmailResetPasswordCode {
//	   string email = 1;
//	   string code = 2;
//	}
//
//	message ResCheckEmailResetPasswordCode {
//	   string nonce = 1;
//	}
//
//	message ReqResetPasswordByEmail {
//	   string email = 1;
//	   string password = 2;
//	   string nonce = 3;
//	}
//
//	message ReqResetPasswordByEmailAndVCode {
//	   string email = 1;
//	   string password = 2;
//	   string code = 3;
//	}
//
//	message ReqBatchGetAccountsByWalletAddrs {
//	   repeated string addrs = 1;
//	}
//
//	message ResBatchGetAccountsByWalletAddrs {
//	   repeated AccountInfo accounts = 1;
//	}
type ReqTelegramLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *ReqTelegramLogin) Reset() {
	*x = ReqTelegramLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqTelegramLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTelegramLogin) ProtoMessage() {}

func (x *ReqTelegramLogin) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTelegramLogin.ProtoReflect.Descriptor instead.
func (*ReqTelegramLogin) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{0}
}

func (x *ReqTelegramLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type ResTelegramLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *ResTelegramLogin) Reset() {
	*x = ResTelegramLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResTelegramLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResTelegramLogin) ProtoMessage() {}

func (x *ResTelegramLogin) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResTelegramLogin.ProtoReflect.Descriptor instead.
func (*ResTelegramLogin) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{1}
}

func (x *ResTelegramLogin) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type ResLoginTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token          string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Energy         uint32       `protobuf:"varint,3,opt,name=energy,proto3" json:"energy,omitempty"`
	EnergyUpdateAt int64        `protobuf:"varint,4,opt,name=energy_update_at,json=energyUpdateAt,proto3" json:"energy_update_at,omitempty"`
}

func (x *ResLoginTest) Reset() {
	*x = ResLoginTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResLoginTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLoginTest) ProtoMessage() {}

func (x *ResLoginTest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLoginTest.ProtoReflect.Descriptor instead.
func (*ResLoginTest) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{2}
}

func (x *ResLoginTest) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResLoginTest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResLoginTest) GetEnergy() uint32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *ResLoginTest) GetEnergyUpdateAt() int64 {
	if x != nil {
		return x.EnergyUpdateAt
	}
	return 0
}

type ReqGenerateLoginToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TgId         uint64 `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	FirstName    string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName     string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	LanguageCode string `protobuf:"bytes,4,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
}

func (x *ReqGenerateLoginToken) Reset() {
	*x = ReqGenerateLoginToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGenerateLoginToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGenerateLoginToken) ProtoMessage() {}

func (x *ReqGenerateLoginToken) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGenerateLoginToken.ProtoReflect.Descriptor instead.
func (*ReqGenerateLoginToken) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{3}
}

func (x *ReqGenerateLoginToken) GetTgId() uint64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *ReqGenerateLoginToken) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ReqGenerateLoginToken) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ReqGenerateLoginToken) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

type ResGenerateLoginToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResGenerateLoginToken) Reset() {
	*x = ResGenerateLoginToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGenerateLoginToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGenerateLoginToken) ProtoMessage() {}

func (x *ResGenerateLoginToken) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGenerateLoginToken.ProtoReflect.Descriptor instead.
func (*ResGenerateLoginToken) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{4}
}

func (x *ResGenerateLoginToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReqLoginByToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqLoginByToken) Reset() {
	*x = ReqLoginByToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginByToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginByToken) ProtoMessage() {}

func (x *ReqLoginByToken) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginByToken.ProtoReflect.Descriptor instead.
func (*ReqLoginByToken) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{5}
}

func (x *ReqLoginByToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResLoginByToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token          string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Energy         uint32       `protobuf:"varint,3,opt,name=energy,proto3" json:"energy,omitempty"`
	EnergyUpdateAt int64        `protobuf:"varint,4,opt,name=energy_update_at,json=energyUpdateAt,proto3" json:"energy_update_at,omitempty"`
}

func (x *ResLoginByToken) Reset() {
	*x = ResLoginByToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResLoginByToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLoginByToken) ProtoMessage() {}

func (x *ResLoginByToken) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLoginByToken.ProtoReflect.Descriptor instead.
func (*ResLoginByToken) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{6}
}

func (x *ResLoginByToken) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResLoginByToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResLoginByToken) GetEnergy() uint32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *ResLoginByToken) GetEnergyUpdateAt() int64 {
	if x != nil {
		return x.EnergyUpdateAt
	}
	return 0
}

var File_grpc_account_proto protoreflect.FileDescriptor

var file_grpc_account_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x54, 0x65,
	0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x54, 0x65, 0x6c, 0x65,
	0x67, 0x72, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x12, 0x28, 0x0a, 0x10, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x52,
	0x65, 0x71, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x65,
	0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x65, 0x71,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79,
	0x12, 0x28, 0x0a, 0x10, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x32, 0x89, 0x02, 0x0a, 0x0e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a,
	0x0d, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x15, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x54,
	0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x11, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x12,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x1a,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x0c, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x1a, 0x14, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_account_proto_rawDescOnce sync.Once
	file_grpc_account_proto_rawDescData = file_grpc_account_proto_rawDesc
)

func file_grpc_account_proto_rawDescGZIP() []byte {
	file_grpc_account_proto_rawDescOnce.Do(func() {
		file_grpc_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_account_proto_rawDescData)
	})
	return file_grpc_account_proto_rawDescData
}

var file_grpc_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_account_proto_goTypes = []interface{}{
	(*ReqTelegramLogin)(nil),      // 0: mpb.ReqTelegramLogin
	(*ResTelegramLogin)(nil),      // 1: mpb.ResTelegramLogin
	(*ResLoginTest)(nil),          // 2: mpb.ResLoginTest
	(*ReqGenerateLoginToken)(nil), // 3: mpb.ReqGenerateLoginToken
	(*ResGenerateLoginToken)(nil), // 4: mpb.ResGenerateLoginToken
	(*ReqLoginByToken)(nil),       // 5: mpb.ReqLoginByToken
	(*ResLoginByToken)(nil),       // 6: mpb.ResLoginByToken
	(*AccountInfo)(nil),           // 7: mpb.AccountInfo
	(*ReqUserId)(nil),             // 8: mpb.ReqUserId
}
var file_grpc_account_proto_depIdxs = []int32{
	7, // 0: mpb.ResTelegramLogin.account:type_name -> mpb.AccountInfo
	7, // 1: mpb.ResLoginTest.account:type_name -> mpb.AccountInfo
	7, // 2: mpb.ResLoginByToken.account:type_name -> mpb.AccountInfo
	0, // 3: mpb.AccountService.TelegramLogin:input_type -> mpb.ReqTelegramLogin
	8, // 4: mpb.AccountService.LoginTest:input_type -> mpb.ReqUserId
	3, // 5: mpb.AccountService.GenerateLoginToken:input_type -> mpb.ReqGenerateLoginToken
	5, // 6: mpb.AccountService.LoginByToken:input_type -> mpb.ReqLoginByToken
	1, // 7: mpb.AccountService.TelegramLogin:output_type -> mpb.ResTelegramLogin
	2, // 8: mpb.AccountService.LoginTest:output_type -> mpb.ResLoginTest
	4, // 9: mpb.AccountService.GenerateLoginToken:output_type -> mpb.ResGenerateLoginToken
	6, // 10: mpb.AccountService.LoginByToken:output_type -> mpb.ResLoginByToken
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_account_proto_init() }
func file_grpc_account_proto_init() {
	if File_grpc_account_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqTelegramLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResTelegramLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResLoginTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGenerateLoginToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGenerateLoginToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoginByToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResLoginByToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_account_proto_goTypes,
		DependencyIndexes: file_grpc_account_proto_depIdxs,
		MessageInfos:      file_grpc_account_proto_msgTypes,
	}.Build()
	File_grpc_account_proto = out.File
	file_grpc_account_proto_rawDesc = nil
	file_grpc_account_proto_goTypes = nil
	file_grpc_account_proto_depIdxs = nil
}
