// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: http_game.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// game
type CReqFight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BossId   uint32 `protobuf:"varint,1,opt,name=boss_id,json=bossId,proto3" json:"boss_id,omitempty"`
	BossUuid uint64 `protobuf:"varint,2,opt,name=boss_uuid,json=bossUuid,proto3" json:"boss_uuid,omitempty"`
}

func (x *CReqFight) Reset() {
	*x = CReqFight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqFight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqFight) ProtoMessage() {}

func (x *CReqFight) ProtoReflect() protoreflect.Message {
	mi := &file_http_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqFight.ProtoReflect.Descriptor instead.
func (*CReqFight) Descriptor() ([]byte, []int) {
	return file_http_game_proto_rawDescGZIP(), []int{0}
}

func (x *CReqFight) GetBossId() uint32 {
	if x != nil {
		return x.BossId
	}
	return 0
}

func (x *CReqFight) GetBossUuid() uint64 {
	if x != nil {
		return x.BossUuid
	}
	return 0
}

type CResFight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Win        bool           `protobuf:"varint,1,opt,name=win,proto3" json:"win,omitempty"`
	Details    []*FightDetail `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	Awards     *CAwards       `protobuf:"bytes,3,opt,name=awards,proto3" json:"awards,omitempty"`
	EnergyCost uint32         `protobuf:"varint,4,opt,name=energy_cost,json=energyCost,proto3" json:"energy_cost,omitempty"`
	Dmg        uint64         `protobuf:"varint,5,opt,name=dmg,proto3" json:"dmg,omitempty"`
	DmgRate    uint64         `protobuf:"varint,6,opt,name=dmg_rate,json=dmgRate,proto3" json:"dmg_rate,omitempty"`
	HiddenBoss *HiddenBoss    `protobuf:"bytes,7,opt,name=hidden_boss,json=hiddenBoss,proto3" json:"hidden_boss,omitempty"`
}

func (x *CResFight) Reset() {
	*x = CResFight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResFight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResFight) ProtoMessage() {}

func (x *CResFight) ProtoReflect() protoreflect.Message {
	mi := &file_http_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResFight.ProtoReflect.Descriptor instead.
func (*CResFight) Descriptor() ([]byte, []int) {
	return file_http_game_proto_rawDescGZIP(), []int{1}
}

func (x *CResFight) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *CResFight) GetDetails() []*FightDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CResFight) GetAwards() *CAwards {
	if x != nil {
		return x.Awards
	}
	return nil
}

func (x *CResFight) GetEnergyCost() uint32 {
	if x != nil {
		return x.EnergyCost
	}
	return 0
}

func (x *CResFight) GetDmg() uint64 {
	if x != nil {
		return x.Dmg
	}
	return 0
}

func (x *CResFight) GetDmgRate() uint64 {
	if x != nil {
		return x.DmgRate
	}
	return 0
}

func (x *CResFight) GetHiddenBoss() *HiddenBoss {
	if x != nil {
		return x.HiddenBoss
	}
	return nil
}

type CResGetEnergy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Energy   uint32 `protobuf:"varint,1,opt,name=energy,proto3" json:"energy,omitempty"`
	UpdateAt int64  `protobuf:"varint,2,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
}

func (x *CResGetEnergy) Reset() {
	*x = CResGetEnergy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResGetEnergy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResGetEnergy) ProtoMessage() {}

func (x *CResGetEnergy) ProtoReflect() protoreflect.Message {
	mi := &file_http_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResGetEnergy.ProtoReflect.Descriptor instead.
func (*CResGetEnergy) Descriptor() ([]byte, []int) {
	return file_http_game_proto_rawDescGZIP(), []int{2}
}

func (x *CResGetEnergy) GetEnergy() uint32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *CResGetEnergy) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type CReqGetHiddenBoss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BossUuid uint64 `protobuf:"varint,1,opt,name=boss_uuid,json=bossUuid,proto3" json:"boss_uuid,omitempty"`
}

func (x *CReqGetHiddenBoss) Reset() {
	*x = CReqGetHiddenBoss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CReqGetHiddenBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReqGetHiddenBoss) ProtoMessage() {}

func (x *CReqGetHiddenBoss) ProtoReflect() protoreflect.Message {
	mi := &file_http_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReqGetHiddenBoss.ProtoReflect.Descriptor instead.
func (*CReqGetHiddenBoss) Descriptor() ([]byte, []int) {
	return file_http_game_proto_rawDescGZIP(), []int{3}
}

func (x *CReqGetHiddenBoss) GetBossUuid() uint64 {
	if x != nil {
		return x.BossUuid
	}
	return 0
}

type CResGetHiddenBoss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HiddenBoss *HiddenBoss `protobuf:"bytes,1,opt,name=hidden_boss,json=hiddenBoss,proto3" json:"hidden_boss,omitempty"`
	Fought     bool        `protobuf:"varint,2,opt,name=fought,proto3" json:"fought,omitempty"`
	FightCd    int64       `protobuf:"varint,3,opt,name=fight_cd,json=fightCd,proto3" json:"fight_cd,omitempty"`
}

func (x *CResGetHiddenBoss) Reset() {
	*x = CResGetHiddenBoss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResGetHiddenBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResGetHiddenBoss) ProtoMessage() {}

func (x *CResGetHiddenBoss) ProtoReflect() protoreflect.Message {
	mi := &file_http_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResGetHiddenBoss.ProtoReflect.Descriptor instead.
func (*CResGetHiddenBoss) Descriptor() ([]byte, []int) {
	return file_http_game_proto_rawDescGZIP(), []int{4}
}

func (x *CResGetHiddenBoss) GetHiddenBoss() *HiddenBoss {
	if x != nil {
		return x.HiddenBoss
	}
	return nil
}

func (x *CResGetHiddenBoss) GetFought() bool {
	if x != nil {
		return x.Fought
	}
	return false
}

func (x *CResGetHiddenBoss) GetFightCd() int64 {
	if x != nil {
		return x.FightCd
	}
	return 0
}

var File_http_game_proto protoreflect.FileDescriptor

var file_http_game_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x09, 0x43, 0x52, 0x65, 0x71, 0x46, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x62, 0x6f, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f,
	0x73, 0x73, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62,
	0x6f, 0x73, 0x73, 0x55, 0x75, 0x69, 0x64, 0x22, 0xef, 0x01, 0x0a, 0x09, 0x43, 0x52, 0x65, 0x73,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x43, 0x41, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x06, 0x61, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6d,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x64, 0x6d, 0x67, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x6d, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x64, 0x6d, 0x67, 0x52, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65,
	0x6e, 0x5f, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x0a, 0x68,
	0x69, 0x64, 0x64, 0x65, 0x6e, 0x42, 0x6f, 0x73, 0x73, 0x22, 0x44, 0x0a, 0x0d, 0x43, 0x52, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22,
	0x30, 0x0a, 0x11, 0x43, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e,
	0x42, 0x6f, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x73, 0x73, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6f, 0x73, 0x73, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x78, 0x0a, 0x11, 0x43, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x48, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e,
	0x5f, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x42, 0x6f, 0x73, 0x73, 0x52, 0x0a, 0x68, 0x69,
	0x64, 0x64, 0x65, 0x6e, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x75, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x6f, 0x75, 0x67, 0x68, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x63, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x43, 0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_game_proto_rawDescOnce sync.Once
	file_http_game_proto_rawDescData = file_http_game_proto_rawDesc
)

func file_http_game_proto_rawDescGZIP() []byte {
	file_http_game_proto_rawDescOnce.Do(func() {
		file_http_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_game_proto_rawDescData)
	})
	return file_http_game_proto_rawDescData
}

var file_http_game_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_http_game_proto_goTypes = []interface{}{
	(*CReqFight)(nil),         // 0: mpb.CReqFight
	(*CResFight)(nil),         // 1: mpb.CResFight
	(*CResGetEnergy)(nil),     // 2: mpb.CResGetEnergy
	(*CReqGetHiddenBoss)(nil), // 3: mpb.CReqGetHiddenBoss
	(*CResGetHiddenBoss)(nil), // 4: mpb.CResGetHiddenBoss
	(*FightDetail)(nil),       // 5: mpb.FightDetail
	(*CAwards)(nil),           // 6: mpb.CAwards
	(*HiddenBoss)(nil),        // 7: mpb.HiddenBoss
}
var file_http_game_proto_depIdxs = []int32{
	5, // 0: mpb.CResFight.details:type_name -> mpb.FightDetail
	6, // 1: mpb.CResFight.awards:type_name -> mpb.CAwards
	7, // 2: mpb.CResFight.hidden_boss:type_name -> mpb.HiddenBoss
	7, // 3: mpb.CResGetHiddenBoss.hidden_boss:type_name -> mpb.HiddenBoss
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_http_game_proto_init() }
func file_http_game_proto_init() {
	if File_http_game_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_http_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqFight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResFight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResGetEnergy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CReqGetHiddenBoss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResGetHiddenBoss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_game_proto_goTypes,
		DependencyIndexes: file_http_game_proto_depIdxs,
		MessageInfos:      file_http_game_proto_msgTypes,
	}.Build()
	File_http_game_proto = out.File
	file_http_game_proto_rawDesc = nil
	file_http_game_proto_goTypes = nil
	file_http_game_proto_depIdxs = nil
}
